kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  image: kindest/node:v1.31.0
- role: worker
  image: kindest/node:v1.31.0
- role: worker
  image: kindest/node:v1.31.0
  extraPortMappings:
  - containerPort: 9999
    hostPort: 9999
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP