kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devs.devops.dev
spec:
  group: devops.dev
  names:
    plural: devs
    singular: devops
    kind: DevOps
    shortNames: 
      - devs
      - ops
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: 
              name: 
                type: string
                description: "Name of the DevOps"
              company:
                type: string
                description: "Company of the DevOps"
              location: 
                type: string
                description: "Location of the DevOps"
