kind: DaemonSet
apiVersion: apps/v1

metadata:
  name: nginx-dmn
  namespace: ns4-nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  # template is a pod.yml
  template: 
    metadata:
      name: nginx-dmn-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80