kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  namespace: ns4-nginx
  labels:
    app: local-pv

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
