kind: Pod
apiVersion: v1 
metadata:
  name: sidecar-container

spec:
  volume:
  - name: shared-logs
    emptyDir: {}

  containers:
  - name: main-apk
    image: busybox:latest
    command: ["sh", "-c", "while true; do echo 'Hello developer' >> /var/log/app.log; sleep 5; done"]

    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/

  - name: sidecar-logs
    image: busybox:latest
    command: ["sh", "-c", "tail -f /var/log/app.log"]

    volumeMounts: 
    - name: shared-logs
      mountPath: /var/log/