kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  
  template:
    metadata:
      name: apache-pod
      labels:
        app: apache
    
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m # 100 millicores, If a node has 4 vCPUs, then 100m is 1/10 of a single vCPU.
              memory: 128Mi # 120 mebibytes, (1 Mi = 1,048,576 bytes(~1Mb)).Equivalent to approximately 125.83 MB.
            limits:
              cpu: 200m
              memory: 256Mi 