kind: Role
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: apache-manager
  namespace: apache

rules:
  - apiGroups: ["", "apps", "batch", "rbac.authorization.k8s.io"] # ["","apps"] 
    resources: ["pods", "deployments", "services"] #["deployment","pod", "service"]
    verbs: ["get"] #["get", "apply", "delete", "watch", "create", "patch"]